//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зоомагазин
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceSet
    {
        public int Id { get; set; }
        public string Term { get; set; }
        public System.DateTime Data { get; set; }
        public long Received { get; set; }
        public long Spent { get; set; }
    }
}
